# Generated by Django 2.2.9 on 2020-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200110_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.IntegerField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
