# Generated by Django 2.2.9 on 2020-01-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200113_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=14),
        ),
    ]
